SELECT * FROM PERSONA
SELECT * FROM PUESTO
SELECT * FROM TIPO_ID
SELECT * FROM EMPLEADO

INSERT INTO PERSONA (COD_PERSONA,NOMBRES,APELLIDOS,FEC_INGRESO,ESTADO,DIRECCION)  
VALUES (100,'ORLANDO','REYNOSO','20-07-2014','A','ZONA 20');

INSERT INTO EMPLEADO (COD_PERSONA,USUARIO,CLAVE,ESTADO,COD_PUESTO,SALARIO_BASE,BONIFICACION,COD_ID_DEFAULT)  
VALUES (100,'OREYNOSO','100','A',1,2200,200,1);
