SELECT B.COD_EMPRESA,B.COD_PROYECTO,B.COD_BODEGA,B.DESC_BODEGA,B.UBICACION,B.ESTADO_BODEGA,
E.COD_EMPRESA,E.NOM_EMPRESA,P.COD_PROYECTO,P.NOM_PROYECTO
FROM BODEGA B,EMPRESA E, PROYECTO P
WHERE 
B.COD_EMPRESA = E.COD_EMPRESA AND
B.COD_PROYECTO = P.COD_PROYECTO

SELECT * FROM BODEGA
SELECT * FROM EMPRESA
SELECT * FROM PROYECTO
