SELECT * FROM DETALLE_MOVIMIENTO_BODEGA

SELECT 
MB.COD_MOVIMIENTO, MB.FEC_MOVIMIENTO,MB.TIPO_MOVIMIENTO,
MB.ESTADO_MOVIMIENTO,MB.TIPO_OPERACION,MB.USUARIO,
DMB.CANTIDAD,
P.ID_PRODUCTO,P.DES_PRODUCTO,P.PRECIO_PRODUCTO,
E.NOM_EMPRESA, PRO.NOM_PROYECTO
FROM MOVIMIENTO_BODEGA MB, DETALLE_MOVIMIENTO_BODEGA DMB, PRODUCTO P, EMPRESA E,PROYECTO PRO
WHERE 
DMB.COD_PRODUCTO = P.COD_PRODUCTO AND
MB.COD_MOVIMIENTO  = DMB.COD_MOVIMIENTO AND
MB.COD_PROYECTO = PRO.COD_PROYECTO

 
 SELECT * FROM MOVIMIENTO_BODEGA
 SELECT * FROM PRODUCTO
 SELECT * FROM EMPRESA
 SELECT * FROM PROYECTO
