
SELECT 
DV.COD_VENTA,DV.CANTIDAD,DV.PRECIO_UNITARIO,
P.ID_PRODUCTO,P.DES_PRODUCTO,
V.COD_BODEGA, V.NO_DOCUMENTO,
V.ESTADO,V.IMPUESTO,V.USUARIO,
EMP.NOM_EMPRESA,
PRO.NOM_PROYECTO,
C.COD_PERSONA,C.DESCRIPCION
FROM DETALLE_VENTA DV,PRODUCTO P,VENTA V,EMPRESA EMP,PROYECTO PRO, CLIENTE C
WHERE 
DV.COD_PRODUCTO = P.COD_PRODUCTO AND
V.COD_PROYECTO = PRO.COD_PROYECTO AND
V.COD_CLIENTE = C.COD_PERSONA


SELECT * FROM CLIENTE

SELECT * FROM VENTA
UPDATE VENTA SET  USUARIO = 'ANGEL ARCHILA' WHERE COD_VENTA = 2
UPDATE CLIENTE SET  DESCRIPCION = 'HOSTIPAL ANGELES' WHERE COD_PERSONA = 1001



