SELECT COD_PRODUCTO,ID_PRODUCTO,DES_PRODUCTO,COD_TIPO_PRODUCTO,ES_SERVICIO,PRECIO_PRODUCTO,ESTADO_PRODUCTO,
FECHA_CREACION,COD_MARCA FROM PRODUCTO

SELECT MAX(COD_PRODUCTO + 1) AS CODP  FROM PRODUCTO
SELECT COD_TIPO_PRODUCTO,DES_TIPO_PRODUCTO, ESTADO_TIP_PROD 
FROM TIPO_PRODUCTO 
WHERE ESTADO_TIP_PROD = 'A'

SELECT * FROM PRODUCTO
SELECT COD_MARCA,DESCRIPCION FROM MARCA_PRODUCTO
SELECT * FROM TIPO_PRODUCTO ORDER BY COD_TIPO_PRODUCTO ASC
SELECT * FROM TIPO_PRODUCTO
