-- Generado por Oracle SQL Developer Data Modeler 4.0.1.836
--   en:        2014-07-06 18:33:39 CST
--   sitio:      Oracle Database 11g
--   tipo:      Oracle Database 11g




CREATE TABLE ACTIVO
  (
    COD_EMPRESA      NUMBER (5) NOT NULL ,
    COD_PROYECTO     NUMBER (5) NOT NULL ,
    COD_ACTIVO       NUMBER (5) ,
    COD_TIPO_ACTIVO  NUMBER (5) NOT NULL ,
    DESCRIPCION      VARCHAR2 (200) ,
    POR_DEPRECIACION NUMBER (2) ,
    SE_DEPRECIA      VARCHAR2 (1) ,
    PRECIO_INICIAL   NUMBER (8,2) ,
    PRECIO_FINAL     NUMBER (8,2) ,
    CANTIDAD         NUMBER (8) ,
    ESTADO           VARCHAR2 (1) ,
    FEC_INGRESO      DATE
  ) ;

CREATE TABLE BODEGA
  (
    COD_EMPRESA   NUMBER (5) NOT NULL ,
    COD_PROYECTO  NUMBER (5) NOT NULL ,
    COD_BODEGA    NUMBER (5) NOT NULL ,
    DESC_BODEGA   VARCHAR2 (150) ,
    UBICACION     VARCHAR2 (500) ,
    FEC_CREACION  DATE ,
    ESTADO_BODEGA VARCHAR2 (1)
  ) ;
-- Error - Index FK1_BODEGA has no columns
ALTER TABLE BODEGA ADD CONSTRAINT PK_BODEGA PRIMARY KEY ( COD_BODEGA, COD_EMPRESA, COD_PROYECTO ) ;

CREATE TABLE CLIENTE
  (
    COD_PERSONA    NUMBER NOT NULL ,
    EMAIL          VARCHAR2 (300) ,
    DESCRIPCION    VARCHAR2 (200) ,
    FEC_INGRESO    DATE ,
    ESTADO         VARCHAR2 (1) ,
    COD_ID_DEFAULT NUMBER (5) NOT NULL
  ) ;
ALTER TABLE CLIENTE ADD CONSTRAINT CLIENTE_PK PRIMARY KEY ( COD_PERSONA ) ;

CREATE TABLE DETALLE_BODEGA
  (
    COD_EMPRESA      NUMBER (5) NOT NULL ,
    COD_PROYECTO     NUMBER (5) NOT NULL ,
    COD_BODEGA       NUMBER (5) NOT NULL ,
    COD_PRODUCTO     NUMBER (5) NOT NULL ,
    CANTIDAD_MINIMA  NUMBER ,
    CANTIDAD_MAXIMA  NUMBER ,
    CANTIDAD_ACTUAL  NUMBER ,
    FECHA_MOVIMIENTO DATE ,
    ESTADO_PRODUCTO  VARCHAR2 (1)
  ) ;
-- Error - Index FK1_DET_BOD has no columns
-- Error - Index FK2_DET_BOD has no columns
-- Error - Index FK3_DET_BOD has no columns
-- Error - Index FK3_DET_BODv2 has no columns
-- Error - Index DETALLE_BODEGA_PRODUCTO_FK has no columns
ALTER TABLE DETALLE_BODEGA ADD CONSTRAINT PK_DET_BOD PRIMARY KEY ( COD_BODEGA, COD_EMPRESA, COD_PROYECTO, COD_PRODUCTO ) ;

CREATE TABLE DETALLE_MOVIMIENTO_BODEGA
  (
    COD_MOVIMIENTO  NUMBER (8) NOT NULL ,
    COD_PRODUCTO    NUMBER (5) NOT NULL ,
    CANTIDAD        NUMBER (8) ,
    PRECIO_UNITARIO NUMBER (8,2)
  ) ;
-- Error - Index FK1_DET_MOV_BOD has no columns
-- Error - Index FK2_DET_MOV_BOD has no columns
-- Error - Index FK1_DET_MOV_BODv2 has no columns
-- Error - Index FK1_DET_MOV_BODv1 has no columns
-- Error - Index FK3_DET_MOV_BOD has no columns
-- Error - Index FK4_DET_MOV_BOD has no columns
-- Error - Index FK5_DET_MOV_BOD has no columns
-- Error - Index DETALLE_MOVIMIENTO_BODEGA_EMPRESA_FK has no columns
-- Error - Index FK2_DET_MOV_BODv1 has no columns
ALTER TABLE DETALLE_MOVIMIENTO_BODEGA ADD CONSTRAINT PK_DET_MOV_BOD PRIMARY KEY ( COD_MOVIMIENTO, COD_PRODUCTO ) ;

CREATE TABLE DETALLE_ORDEN_COMPRA
  (
    COD_ORDEN       NUMBER (5) NOT NULL ,
    COD_PRODUCTO    NUMBER (5) NOT NULL ,
    CANTIDAD        NUMBER (8) ,
    PRECIO_UNITARIO NUMBER (8,2) ,
    IMPUESTO        NUMBER (2)
  ) ;
ALTER TABLE DETALLE_ORDEN_COMPRA ADD CONSTRAINT DETALLE_ORDEN_COMPRA_PK PRIMARY KEY ( COD_ORDEN ) ;

CREATE TABLE DETALLE_VENTA
  (
    COD_VENTA       NUMBER (5) NOT NULL ,
    COD_PRODUCTO    NUMBER (5) NOT NULL ,
    CANTIDAD        NUMBER (8) ,
    PRECIO_UNITARIO NUMBER (8,2)
  ) ;
ALTER TABLE DETALLE_VENTA ADD CONSTRAINT DETALLE_VENTA_PK PRIMARY KEY ( COD_VENTA ) ;

CREATE TABLE EMPLEADO
  (
    COD_PERSONA    NUMBER NOT NULL ,
    USUARIO        VARCHAR2 (50) ,
    CLAVE          VARCHAR2 (20) ,
    ESTADO         VARCHAR2 (1) ,
    COD_PUESTO     NUMBER (5) NOT NULL ,
    SALARIO_BASE   NUMBER (10,2) ,
    BONIFICACION   NUMBER (8,2) ,
    COD_ID_DEFAULT NUMBER (5) NOT NULL
  ) ;
ALTER TABLE EMPLEADO ADD CONSTRAINT USUARIO_PK PRIMARY KEY ( COD_PERSONA ) ;

CREATE TABLE EMPRESA
  (
    COD_EMPRESA          NUMBER (5) NOT NULL ,
    NOM_EMPRESA          VARCHAR2 (200) ,
    DIRECCION            VARCHAR2 (300) ,
    IDENTIFICACION_LEGAL VARCHAR2 (20) ,
    ESTADO               VARCHAR2 (1)
  ) ;
ALTER TABLE EMPRESA ADD CONSTRAINT EMPRESA_PK PRIMARY KEY ( COD_EMPRESA ) ;

CREATE TABLE MOVIMIENTO_BODEGA
  (
    COD_EMPRESA        NUMBER (5) NOT NULL ,
    COD_PROYECTO       NUMBER (5) NOT NULL ,
    COD_BODEGA         NUMBER (5) NOT NULL ,
    COD_MOVIMIENTO     NUMBER (8) NOT NULL ,
    FEC_MOVIMIENTO     DATE ,
    USUARIO_REGISTRA   VARCHAR2 (16) NOT NULL ,
    TIPO_MOVIMIENTO    VARCHAR2 (1) ,
    USUARIO_MOVIMIENTO VARCHAR2 (16) ,
    ESTADO_MOVIMIENTO  VARCHAR2 (1) ,
    TIPO_OPERACION     VARCHAR2 (1) ,
    USUARIO            VARCHAR2 (50)
  ) ;
-- Error - Index FK1_MOV_BOD has no columns
-- Error - Index FK2_MOV_BOD has no columns
-- Error - Index FK1_MOV_BODv2 has no columns
-- Error - Index FK2_MOV_BODv2 has no columns
-- Error - Index FK3_MOV_BOD has no columns
ALTER TABLE MOVIMIENTO_BODEGA ADD CONSTRAINT PK_MOV_BOD PRIMARY KEY ( COD_MOVIMIENTO ) ;

CREATE TABLE ORDEN_COMPRA
  (
    COD_EMPRESA        NUMBER (5) NOT NULL ,
    COD_PROYECTO       NUMBER (5) NOT NULL ,
    COD_BODEGA         NUMBER (5) NOT NULL ,
    COD_ORDEN          NUMBER (5) NOT NULL ,
    COD_MOVIMIENTO_BOD NUMBER (8) ,
    IND_APLICADA       VARCHAR2 (1) ,
    AFECTA_BODEGA      VARCHAR2 (1) ,
    ESTADO             VARCHAR2 (1) ,
    USUARIO            VARCHAR2 (50)
  ) ;
ALTER TABLE ORDEN_COMPRA ADD CONSTRAINT ORDEN_COMPRA_PK PRIMARY KEY ( COD_ORDEN ) ;

CREATE TABLE PERSONA
  (
    COD_PERSONA NUMBER NOT NULL ,
    NOMBRES     VARCHAR2 (300) ,
    APELLIDOS   VARCHAR2 (300) ,
    FEC_INGRESO DATE ,
    ESTADO      VARCHAR2 (1) ,
    DIRECCION   VARCHAR2 (300)
  ) ;
ALTER TABLE PERSONA ADD CONSTRAINT PK_PERSONA PRIMARY KEY ( COD_PERSONA ) ;

CREATE TABLE PERSONA_CONTACTO
  (
    COD_CONTACTO      NUMBER (5) NOT NULL ,
    COD_TIPO_CONTACTO NUMBER (5) ,
    COD_PERSONA       NUMBER NOT NULL ,
    DESCRIPCION       VARCHAR2 (200) ,
    CONTACTO          VARCHAR2 (200) ,
    ESTADO            VARCHAR2 (1)
  ) ;
ALTER TABLE PERSONA_CONTACTO ADD CONSTRAINT PERSONA_CONTACTO_PK PRIMARY KEY ( COD_CONTACTO ) ;

CREATE TABLE PERSONA_ID
  (
    COD_ID             NUMBER (5) NOT NULL ,
    COD_PERSONA        NUMBER NOT NULL ,
    NUM_IDENTIFICACION VARCHAR2 (25) ,
    DESCRIPCION        VARCHAR2 (100)
  ) ;
ALTER TABLE PERSONA_ID ADD CONSTRAINT PERSONA_ID_PK PRIMARY KEY ( COD_ID, COD_PERSONA ) ;

CREATE TABLE PRODUCTO
  (
    COD_PRODUCTO      NUMBER (5) NOT NULL ,
    ID_PRODUCTO       VARCHAR2 (20) NOT NULL ,
    DES_PRODUCTO      VARCHAR2 (150) ,
    COD_TIPO_PRODUCTO NUMBER NOT NULL ,
    ES_SERVICIO       VARCHAR2 (1) ,
    PRECIO_PRODUCTO   NUMBER (8,2) ,
    ESTADO_PRODUCTO   VARCHAR2 (1) ,
    FECHA_CREACION    DATE
  ) ;
ALTER TABLE PRODUCTO ADD CONSTRAINT PRODUCTO_PK PRIMARY KEY ( COD_PRODUCTO ) ;

CREATE TABLE PROVEEDOR
  (
    COD_PERSONA    NUMBER NOT NULL ,
    EMAIL          VARCHAR2 (200) ,
    COD_ID_DEFAULT NUMBER (5) ,
    DESCRIPCION    VARCHAR2 (300) ,
    FEC_INGRESO    DATE ,
    ESTADO         VARCHAR2 (2)
  ) ;
ALTER TABLE PROVEEDOR ADD CONSTRAINT PROVEEDOR_PK PRIMARY KEY ( COD_PERSONA ) ;

CREATE TABLE PROYECTO
  (
    COD_EMPRESA  NUMBER (5) NOT NULL ,
    COD_PROYECTO NUMBER (5) NOT NULL ,
    NOM_PROYECTO VARCHAR2 (200) ,
    DIRECCION    VARCHAR2 (200) ,
    ESTADO       VARCHAR2 (1)
  ) ;
ALTER TABLE PROYECTO ADD CONSTRAINT SUCURSAL_PK PRIMARY KEY ( COD_EMPRESA, COD_PROYECTO ) ;

CREATE TABLE PUESTO
  (
    COD_PUESTO NUMBER (5) NOT NULL ,
    DES_PUESTO VARCHAR2 (100) ,
    ESTADO     VARCHAR2 (1)
  ) ;
ALTER TABLE PUESTO ADD CONSTRAINT PUESTO_PK PRIMARY KEY ( COD_PUESTO ) ;

CREATE TABLE TIPO_ACTIVO
  (
    COD_TIPO_ACTIVO NUMBER (5) NOT NULL ,
    DESCRIPCION     VARCHAR2 (200) ,
    ESTADO          VARCHAR2 (1) ,
    FEC_CREACION    DATE
  ) ;
ALTER TABLE TIPO_ACTIVO ADD CONSTRAINT TIPO_ACTIVO_PK PRIMARY KEY ( COD_TIPO_ACTIVO ) ;

CREATE TABLE TIPO_CONTACTO
  (
    COD_TIPO_CONTACTO NUMBER (5) NOT NULL ,
    DESCRIPCION       VARCHAR2 (200) ,
    ESTADO            VARCHAR2
  ) ;
ALTER TABLE TIPO_CONTACTO ADD CONSTRAINT TIPO_CONTACTO_PK PRIMARY KEY ( COD_TIPO_CONTACTO ) ;

CREATE TABLE TIPO_ID
  (
    COD_ID      NUMBER (5) NOT NULL ,
    DES_ID      VARCHAR2 (200) ,
    FEC_INGRESO DATE ,
    ESTADO_ID   VARCHAR2 (1)
  ) ;
ALTER TABLE TIPO_ID ADD CONSTRAINT TIPO_ID_PK PRIMARY KEY ( COD_ID ) ;

CREATE TABLE TIPO_PRODUCTO
  (
    COD_TIPO_PRODUCTO NUMBER NOT NULL ,
    DES_TIPO_PRODUCTO VARCHAR2 (150) ,
    ESTADO_TIP_PROD   VARCHAR2 (1)
  ) ;
ALTER TABLE TIPO_PRODUCTO ADD CONSTRAINT PK_TIP_PRO PRIMARY KEY ( COD_TIPO_PRODUCTO ) ;

CREATE TABLE VENTA
  (
    COD_VENTA          NUMBER (5) NOT NULL ,
    COD_EMPRESA        NUMBER (5) NOT NULL ,
    COD_PROYECTO       NUMBER (5) NOT NULL ,
    COD_BODEGA         NUMBER (5) NOT NULL ,
    COD_MOVIMIENTO_BOD NUMBER (8) NOT NULL ,
    NO_DOCUMENTO       VARCHAR2 ,
    IND_APLICADA       VARCHAR2 (1) ,
    ESTADO             VARCHAR2 (1) ,
    IMPUESTO           NUMBER (2) ,
    USUARIO            VARCHAR2 (50)
  ) ;
ALTER TABLE VENTA ADD CONSTRAINT VENTA_PK PRIMARY KEY ( COD_VENTA ) ;

ALTER TABLE CLIENTE ADD CONSTRAINT CLIENTE_TIPO_ID_FK FOREIGN KEY ( COD_ID_DEFAULT ) REFERENCES TIPO_ID ( COD_ID ) ;

ALTER TABLE ACTIVO ADD CONSTRAINT FK1_ACT FOREIGN KEY ( COD_EMPRESA, COD_PROYECTO ) REFERENCES PROYECTO ( COD_EMPRESA, COD_PROYECTO ) ;

ALTER TABLE BODEGA ADD CONSTRAINT FK1_BODEGA FOREIGN KEY ( COD_EMPRESA, COD_PROYECTO ) REFERENCES PROYECTO ( COD_EMPRESA, COD_PROYECTO ) ;

ALTER TABLE CLIENTE ADD CONSTRAINT FK1_CLIE FOREIGN KEY ( COD_PERSONA ) REFERENCES PERSONA ( COD_PERSONA ) ;

ALTER TABLE DETALLE_BODEGA ADD CONSTRAINT FK1_DET_BOD FOREIGN KEY ( COD_BODEGA, COD_EMPRESA, COD_PROYECTO ) REFERENCES BODEGA ( COD_BODEGA, COD_EMPRESA, COD_PROYECTO ) ;

ALTER TABLE DETALLE_MOVIMIENTO_BODEGA ADD CONSTRAINT FK1_DET_MOV_BOD FOREIGN KEY ( COD_MOVIMIENTO ) REFERENCES MOVIMIENTO_BODEGA ( COD_MOVIMIENTO ) ;

ALTER TABLE DETALLE_MOVIMIENTO_BODEGA ADD CONSTRAINT FK1_DET_MOV_BODv2 FOREIGN KEY ( COD_PRODUCTO ) REFERENCES PRODUCTO ( COD_PRODUCTO ) ;

ALTER TABLE DETALLE_ORDEN_COMPRA ADD CONSTRAINT FK1_DET_ORD_COM FOREIGN KEY ( COD_ORDEN ) REFERENCES ORDEN_COMPRA ( COD_ORDEN ) ;

ALTER TABLE DETALLE_VENTA ADD CONSTRAINT FK1_DET_VEN FOREIGN KEY ( COD_VENTA ) REFERENCES VENTA ( COD_VENTA ) ;

ALTER TABLE EMPLEADO ADD CONSTRAINT FK1_EMP FOREIGN KEY ( COD_PERSONA ) REFERENCES PERSONA ( COD_PERSONA ) ;

ALTER TABLE MOVIMIENTO_BODEGA ADD CONSTRAINT FK1_MOV_BOD FOREIGN KEY ( COD_BODEGA, COD_EMPRESA, COD_PROYECTO ) REFERENCES BODEGA ( COD_BODEGA, COD_EMPRESA, COD_PROYECTO ) ;

ALTER TABLE ORDEN_COMPRA ADD CONSTRAINT FK1_ORD_COM FOREIGN KEY ( COD_BODEGA, COD_EMPRESA, COD_PROYECTO ) REFERENCES BODEGA ( COD_BODEGA, COD_EMPRESA, COD_PROYECTO ) ;

ALTER TABLE PERSONA_CONTACTO ADD CONSTRAINT FK1_PER_CON FOREIGN KEY ( COD_PERSONA ) REFERENCES PERSONA ( COD_PERSONA ) ;

ALTER TABLE PERSONA_ID ADD CONSTRAINT FK1_PER_ID FOREIGN KEY ( COD_ID ) REFERENCES TIPO_ID ( COD_ID ) ;

ALTER TABLE PRODUCTO ADD CONSTRAINT FK1_PRODUCTO FOREIGN KEY ( COD_TIPO_PRODUCTO ) REFERENCES TIPO_PRODUCTO ( COD_TIPO_PRODUCTO ) ;

ALTER TABLE VENTA ADD CONSTRAINT FK1_VENTA FOREIGN KEY ( COD_BODEGA, COD_EMPRESA, COD_PROYECTO ) REFERENCES BODEGA ( COD_BODEGA, COD_EMPRESA, COD_PROYECTO ) ;

ALTER TABLE ACTIVO ADD CONSTRAINT FK2_ACT FOREIGN KEY ( COD_TIPO_ACTIVO ) REFERENCES TIPO_ACTIVO ( COD_TIPO_ACTIVO ) ;

ALTER TABLE DETALLE_BODEGA ADD CONSTRAINT FK2_DET_BOD FOREIGN KEY ( COD_PRODUCTO ) REFERENCES PRODUCTO ( COD_PRODUCTO ) ;

ALTER TABLE DETALLE_ORDEN_COMPRA ADD CONSTRAINT FK2_DET_ORD_COM FOREIGN KEY ( COD_PRODUCTO ) REFERENCES PRODUCTO ( COD_PRODUCTO ) ;

ALTER TABLE DETALLE_VENTA ADD CONSTRAINT FK2_DET_VEN FOREIGN KEY ( COD_PRODUCTO ) REFERENCES PRODUCTO ( COD_PRODUCTO ) ;

ALTER TABLE EMPLEADO ADD CONSTRAINT FK2_EMP FOREIGN KEY ( COD_ID_DEFAULT ) REFERENCES TIPO_ID ( COD_ID ) ;

ALTER TABLE PERSONA_CONTACTO ADD CONSTRAINT FK2_PER_CON FOREIGN KEY ( COD_CONTACTO ) REFERENCES TIPO_CONTACTO ( COD_TIPO_CONTACTO ) ;

ALTER TABLE PERSONA_ID ADD CONSTRAINT FK2_PER_ID FOREIGN KEY ( COD_PERSONA ) REFERENCES PERSONA ( COD_PERSONA ) ;

ALTER TABLE VENTA ADD CONSTRAINT FK2_VENTA FOREIGN KEY ( COD_MOVIMIENTO_BOD ) REFERENCES MOVIMIENTO_BODEGA ( COD_MOVIMIENTO ) ;

ALTER TABLE EMPLEADO ADD CONSTRAINT FK3_EMP FOREIGN KEY ( COD_PUESTO ) REFERENCES PUESTO ( COD_PUESTO ) ;

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE ORDEN_COMPRA ADD CONSTRAINT ORDEN_COMPRA_MOVIMIENTO_BODEGA_FK FOREIGN KEY ( COD_MOVIMIENTO_BOD ) REFERENCES MOVIMIENTO_BODEGA ( COD_MOVIMIENTO ) ;

ALTER TABLE PROVEEDOR ADD CONSTRAINT PROVEEDOR_PERSONA_FK FOREIGN KEY ( COD_PERSONA ) REFERENCES PERSONA ( COD_PERSONA ) ;

ALTER TABLE PROYECTO ADD CONSTRAINT SUCURSAL_EMPRESA_FK FOREIGN KEY ( COD_EMPRESA ) REFERENCES EMPRESA ( COD_EMPRESA ) ;

CREATE OR REPLACE TRIGGER FKNTO_ORDEN_COMPRA BEFORE
  UPDATE OF COD_MOVIMIENTO_BOD ON ORDEN_COMPRA FOR EACH ROW BEGIN IF :old.COD_MOVIMIENTO_BOD IS NOT NULL THEN raise_application_error(-20225,'Non Transferable FK constraint ORDEN_COMPRA_MOVIMIENTO_BODEGA_FK on table ORDEN_COMPRA is violated');
END IF;
END;
/


-- Informe de Resumen de Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                            23
-- CREATE INDEX                             0
-- ALTER TABLE                             50
-- CREATE VIEW                              0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           1
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ERRORS                                  21
-- WARNINGS                                 0
